### ISSUE TITLE
v2.0.6 does not work

### ISSUE THREAD

**Issue by mrdiega** [ABKAM2023/CS2-RanksPoints#16]
CS2-RanksPoints 2.0.6
css v130

Tested with bots. Points are not awarded, commands do not work
errors:
```
[All Chat][diega.WinWin^^ (79255768)]: !rank
20:04:46 [EROR] (cssharp:Core) Error invoking callback
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at RanksPointsNamespace.RanksPoints.OnRankCommand(CCSPlayerController player, CommandInfo command) in C:\Users\Ruslans\Desktop\CS2-RanksPoints\RU\source\RanksPoints.cs:line 1508
   at CounterStrikeSharp.API.Core.BasePlugin.<>c__DisplayClass41_0.<AddCommand>b__0(Int32 i, IntPtr ptr) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/BasePlugin.cs:line 259
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at CounterStrikeSharp.API.Core.FunctionReference.<>c__DisplayClass3_0.<.ctor>b__0(fxScriptContext* context) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/FunctionReference.cs:line 82
20:04:53 [EROR] (cssharp:Core) Error invoking callback
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at RanksPointsNamespace.RanksPoints.OnPlayerDeath(EventPlayerDeath deathEvent, GameEventInfo info) in C:\Users\Ruslans\Desktop\CS2-RanksPoints\RU\source\RanksPoints.cs:line 993
   at InvokeStub_GameEventHandler`1.Invoke(Object, Object, IntPtr*)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at CounterStrikeSharp.API.Core.FunctionReference.<>c__DisplayClass3_0.<.ctor>b__0(fxScriptContext* context) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/FunctionReference.cs:line 82
20:04:53 [EROR] (cssharp:Core) Error invoking callback
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at RanksPointsNamespace.RanksPoints.OnPlayerMVP(EventRoundMvp mvpEvent, GameEventInfo info) in C:\Users\Ruslans\Desktop\CS2-RanksPoints\RU\source\RanksPoints.cs:line 963
   at InvokeStub_GameEventHandler`1.Invoke(Object, Object, IntPtr*)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at CounterStrikeSharp.API.Core.FunctionReference.<>c__DisplayClass3_0.<.ctor>b__0(fxScriptContext* context) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/FunctionReference.cs:line 82
20:04:53 [EROR] (cssharp:Core) Error invoking callback
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at RanksPointsNamespace.RanksPoints.OnRoundEnd(EventRoundEnd roundEndEvent, GameEventInfo info) in C:\Users\Ruslans\Desktop\CS2-RanksPoints\RU\source\RanksPoints.cs:line 912
   at InvokeStub_GameEventHandler`1.Invoke(Object, Object, IntPtr*)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at CounterStrikeSharp.API.Core.FunctionReference.<>c__DisplayClass3_0.<.ctor>b__0(fxScriptContext* context) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/FunctionReference.cs:line 82
[Auto Balance Plugin] -> Round ended, trying auto-balance
"Steel<0><BOT><CT>" OnPreResetRound => CTMDBG, team 3  will switch 0 297.38
"diega.WinWin^^<2><[U:1:79255768]><TERRORIST>" OnPreResetRound => CTMDBG, team 2  will switch 0 297.38
20:04:59 [EROR] (cssharp:Core) Error invoking callback
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at RanksPointsNamespace.RanksPoints.OnRoundStart(EventRoundStart roundStartEvent, GameEventInfo info) in C:\Users\Ruslans\Desktop\CS2-RanksPoints\RU\source\RanksPoints.cs:line 719
   at InvokeStub_GameEventHandler`1.Invoke(Object, Object, IntPtr*)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at CounterStrikeSharp.API.Core.FunctionReference.<>c__DisplayClass3_0.<.ctor>b__0(fxScriptContext* context) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/FunctionReference.cs:line 82
SV: 'diega.WinWin^^' (tick 19033) CQ:  catching up - trying to trim queue containing 0 commands
sv: Firing first shot, sv tick 19289, but no attack information present in command 11326 with 4 history entries
    command tick: 19288
    attack1_start_history_index: -1
    attack2_start_history_index: -1
    attack3_start_history_index: -1
    history: 19288.982422
    history: 19289.119141
    history: 19289.357422
    history: 19289.494141
sv: Firing first shot, sv tick 19289, but no attack information present in command 11326 with 4 history entries
    command tick: 19288
    attack1_start_history_index: -1
    attack2_start_history_index: -1
    attack3_start_history_index: -1
    history: 19288.982422
    history: 19289.119141
    history: 19289.357422
    history: 19289.494141
20:05:12 [EROR] (cssharp:Core) Error invoking callback
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at RanksPointsNamespace.RanksPoints.OnPlayerDeath(EventPlayerDeath deathEvent, GameEventInfo info) in C:\Users\Ruslans\Desktop\CS2-RanksPoints\RU\source\RanksPoints.cs:line 993
   at InvokeStub_GameEventHandler`1.Invoke(Object, Object, IntPtr*)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at CounterStrikeSharp.API.Core.FunctionReference.<>c__DisplayClass3_0.<.ctor>b__0(fxScriptContext* context) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/FunctionReference.cs:line 82
20:05:12 [EROR] (cssharp:Core) Error invoking callback
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at RanksPointsNamespace.RanksPoints.OnPlayerMVP(EventRoundMvp mvpEvent, GameEventInfo info) in C:\Users\Ruslans\Desktop\CS2-RanksPoints\RU\source\RanksPoints.cs:line 963
   at InvokeStub_GameEventHandler`1.Invoke(Object, Object, IntPtr*)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at CounterStrikeSharp.API.Core.FunctionReference.<>c__DisplayClass3_0.<.ctor>b__0(fxScriptContext* context) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/FunctionReference.cs:line 82
20:05:12 [EROR] (cssharp:Core) Error invoking callback
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at RanksPointsNamespace.RanksPoints.OnRoundEnd(EventRoundEnd roundEndEvent, GameEventInfo info) in C:\Users\Ruslans\Desktop\CS2-RanksPoints\RU\source\RanksPoints.cs:line 912
   at InvokeStub_GameEventHandler`1.Invoke(Object, Object, IntPtr*)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at CounterStrikeSharp.API.Core.FunctionReference.<>c__DisplayClass3_0.<.ctor>b__0(fxScriptContext* context) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/FunctionReference.cs:line 82
[Auto Balance Plugin] -> Round ended, trying auto-balance
"Steel<0><BOT><CT>" OnPreResetRound => CTMDBG, team 3  will switch 0 315.89
"diega.WinWin^^<2><[U:1:79255768]><TERRORIST>" OnPreResetRound => CTMDBG, team 2  will switch 0 315.89
20:05:18 [EROR] (cssharp:Core) Error invoking callback
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at RanksPointsNamespace.RanksPoints.OnRoundStart(EventRoundStart roundStartEvent, GameEventInfo info) in C:\Users\Ruslans\Desktop\CS2-RanksPoints\RU\source\RanksPoints.cs:line 719
   at InvokeStub_GameEventHandler`1.Invoke(Object, Object, IntPtr*)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at CounterStrikeSharp.API.Core.FunctionReference.<>c__DisplayClass3_0.<.ctor>b__0(fxScriptContext* context) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/FunctionReference.cs:line 82
```

**Comment by ABKAM2023** [comment]
I just tested this version on the test server, and everything is working correctly. Are you sure you specified the database correctly? Were the data entered accurately? Were the tables created in the database?

**Comment by mrdiega** [comment]
![image](https://github.com/ABKAM2023/CS2-RanksPoints/assets/79888956/4b702a3d-f57e-4423-a024-13c9bd6bac47)

**Comment by maxXx1** [comment]
i have exactly the same problem? where was the mistake? did you manage to solve it somehow @mrdiega ?

![image](https://github.com/ABKAM2023/CS2-RanksPoints/assets/10677165/c2251902-5784-496d-b3f0-e2e19e75c8a4)
