### ISSUE TITLE
Errors in console

### ISSUE THREAD

**Issue by AZzeLx** [ABKAM2023/CS2-RanksPoints#2]
`System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.Collections.Generic.KeyNotFoundException: The given key '76561198255033754' was not present in the dictionary.
   at RankPointsPlugin.RankPointsPlugin.OnRoundEnd(EventRoundEnd roundEndEvent, GameEventInfo info) in C:\Users\azzel\OneDrive\Desktop\CS2-RanksPoints-main\source\RanksPoints.cs:line 561
   at InvokeStub_GameEventHandler`1.Invoke(Object, Object, IntPtr*)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at CounterStrikeSharp.API.Core.FunctionReference.<>c__DisplayClass3_0.<.ctor>b__0(fxScriptContext* context) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/FunctionReference.cs:line 81`

**Comment by ABKAM2023** [comment]
Hello, I will fix this error in the next update
